version: '3.7'
services:
  velody:
    image: velody
    container_name: velody
    restart: always
    build: .
    environment:
      - BOT_TOKEN=$BOT_TOKEN
      - GOOGLE_AUTH_FILE=account.json
      - OPENAI_ORG=$OPENAI_ORG
      - OPENAI_KEY=$OPENAI_KEY
