apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
images:
  - name: velody
    newName: velody
    newTag: v1

configMapGenerator:
  - name: velody-config
    literals:
      - BOT_TOKEN=token
