name: Deploy Velody

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build-and-push:
    runs-on: self-hosted
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: 'ghcr.io'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ghcr.io/linusromland/velody

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  update-deployment:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Kustomize
        uses: docker://k8s.gcr.io/kustomize/kustomize:v3.8.7
        with:
          args: edit set image ghcr.io/linusromland/velody=ghcr.io/linusromland/velody:master-${{ github.run_number }}
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add kustomization.yaml
          git commit -m "Update image tag to ${{ github.run_number }}"
          git push https://linusromland:${{ secrets.GITHUB_TOKEN }}@github.com/linusromland/Velody.git HEAD:<branch>
